// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package user_db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CurrentStatus string

const (
	CurrentStatusPENDING CurrentStatus = "PENDING"
	CurrentStatusSUCCESS CurrentStatus = "SUCCESS"
	CurrentStatusFAILED  CurrentStatus = "FAILED"
	CurrentStatusUNKNOWN CurrentStatus = "UNKNOWN"
)

func (e *CurrentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CurrentStatus(s)
	case string:
		*e = CurrentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CurrentStatus: %T", src)
	}
	return nil
}

type NullCurrentStatus struct {
	CurrentStatus CurrentStatus `json:"current_status"`
	Valid         bool          `json:"valid"` // Valid is true if CurrentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCurrentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CurrentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CurrentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCurrentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CurrentStatus), nil
}

type GikiWalletAuditEventType string

const (
	GikiWalletAuditEventTypeTOPUPREQUEST    GikiWalletAuditEventType = "TOPUP_REQUEST"
	GikiWalletAuditEventTypeCARDCALLBACK    GikiWalletAuditEventType = "CARD_CALLBACK"
	GikiWalletAuditEventTypeMWALLETCALLBACK GikiWalletAuditEventType = "MWALLET_CALLBACK"
	GikiWalletAuditEventTypeINQUIRYRESULT   GikiWalletAuditEventType = "INQUIRY_RESULT"
)

func (e *GikiWalletAuditEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GikiWalletAuditEventType(s)
	case string:
		*e = GikiWalletAuditEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for GikiWalletAuditEventType: %T", src)
	}
	return nil
}

type NullGikiWalletAuditEventType struct {
	GikiWalletAuditEventType GikiWalletAuditEventType `json:"giki_wallet_audit_event_type"`
	Valid                    bool                     `json:"valid"` // Valid is true if GikiWalletAuditEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGikiWalletAuditEventType) Scan(value interface{}) error {
	if value == nil {
		ns.GikiWalletAuditEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GikiWalletAuditEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGikiWalletAuditEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GikiWalletAuditEventType), nil
}

type GikiTransportDriver struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	PhoneNumber   string      `json:"phone_number"`
	LicenseNumber pgtype.Text `json:"license_number"`
	IsActive      pgtype.Bool `json:"is_active"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type GikiTransportRoute struct {
	ID                             uuid.UUID   `json:"id"`
	Name                           string      `json:"name"`
	OriginStopID                   uuid.UUID   `json:"origin_stop_id"`
	DestinationStopID              uuid.UUID   `json:"destination_stop_id"`
	IsActive                       pgtype.Bool `json:"is_active"`
	DefaultBookingOpenOffsetHours  pgtype.Int4 `json:"default_booking_open_offset_hours"`
	DefaultBookingCloseOffsetHours pgtype.Int4 `json:"default_booking_close_offset_hours"`
	CreatedAt                      time.Time   `json:"created_at"`
}

type GikiTransportRouteMasterStop struct {
	ID                   uuid.UUID `json:"id"`
	RouteID              uuid.UUID `json:"route_id"`
	StopID               uuid.UUID `json:"stop_id"`
	DefaultSequenceOrder int32     `json:"default_sequence_order"`
	IsDefaultActive      bool      `json:"is_default_active"`
	CreatedAt            time.Time `json:"created_at"`
}

type GikiTransportRouteWeeklySchedule struct {
	ID            uuid.UUID          `json:"id"`
	RouteID       uuid.UUID          `json:"route_id"`
	DayOfWeek     int32              `json:"day_of_week"`
	DepartureTime pgtype.Time        `json:"departure_time"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type GikiTransportStop struct {
	ID        uuid.UUID `json:"id"`
	Address   string    `json:"address"`
	CreatedAt time.Time `json:"created_at"`
}

type GikiTransportTrip struct {
	ID              uuid.UUID      `json:"id"`
	RouteID         uuid.UUID      `json:"route_id"`
	DriverID        uuid.UUID      `json:"driver_id"`
	DepartureTime   time.Time      `json:"departure_time"`
	BookingOpensAt  time.Time      `json:"booking_opens_at"`
	BookingClosesAt time.Time      `json:"booking_closes_at"`
	TotalCapacity   int32          `json:"total_capacity"`
	AvailableSeats  int32          `json:"available_seats"`
	BasePrice       pgtype.Numeric `json:"base_price"`
	Status          pgtype.Text    `json:"status"`
	BookingStatus   string         `json:"booking_status"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type GikiTransportTripStop struct {
	ID            uuid.UUID `json:"id"`
	TripID        uuid.UUID `json:"trip_id"`
	StopID        uuid.UUID `json:"stop_id"`
	SequenceOrder int32     `json:"sequence_order"`
	CreatedAt     time.Time `json:"created_at"`
}

type GikiWalletAdmin struct {
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
	Permissions []string  `json:"permissions"`
}

type GikiWalletEmployeeProfile struct {
	UserID      uuid.UUID   `json:"user_id"`
	EmployeeID  string      `json:"employee_id"`
	Designation pgtype.Text `json:"designation"`
	Department  pgtype.Text `json:"department"`
}

type GikiWalletGatewayTransaction struct {
	ID             uuid.UUID     `json:"id"`
	UserID         uuid.UUID     `json:"user_id"`
	IdempotencyKey uuid.UUID     `json:"idempotency_key"`
	BillRefID      string        `json:"bill_ref_id"`
	TxnRefNo       string        `json:"txn_ref_no"`
	PaymentMethod  string        `json:"payment_method"`
	GatewayRrn     pgtype.Text   `json:"gateway_rrn"`
	Status         CurrentStatus `json:"status"`
	Amount         int64         `json:"amount"`
	RawResponse    []byte        `json:"raw_response"`
	IsPolling      pgtype.Bool   `json:"is_polling"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
}

type GikiWalletLedger struct {
	ID            uuid.UUID `json:"id"`
	WalletID      uuid.UUID `json:"wallet_id"`
	Amount        int64     `json:"amount"`
	BalanceAfter  int64     `json:"balance_after"`
	TransactionID uuid.UUID `json:"transaction_id"`
	RowHash       string    `json:"row_hash"`
	CreatedAt     time.Time `json:"created_at"`
}

type GikiWalletPaymentAuditLog struct {
	ID           uuid.UUID                `json:"id"`
	EventType    GikiWalletAuditEventType `json:"event_type"`
	RawPayload   []byte                   `json:"raw_payload"`
	TxnRefNo     pgtype.Text              `json:"txn_ref_no"`
	GatewayRef   pgtype.Text              `json:"gateway_ref"`
	UserID       pgtype.UUID              `json:"user_id"`
	Processed    pgtype.Bool              `json:"processed"`
	ProcessedAt  pgtype.Timestamptz       `json:"processed_at"`
	ProcessError pgtype.Text              `json:"process_error"`
	RetryCount   pgtype.Int4              `json:"retry_count"`
	ReceivedAt   time.Time                `json:"received_at"`
}

type GikiWalletRefreshToken struct {
	ID              uuid.UUID        `json:"id"`
	TokenHash       string           `json:"token_hash"`
	ExpiresAt       pgtype.Timestamp `json:"expires_at"`
	RevokedAt       pgtype.Timestamp `json:"revoked_at"`
	ReplacedByToken pgtype.Text      `json:"replaced_by_token"`
	DeviceInfo      pgtype.Text      `json:"device_info"`
	IpAddress       pgtype.Text      `json:"ip_address"`
	UserID          uuid.UUID        `json:"user_id"`
	CreatedAt       time.Time        `json:"created_at"`
	UpdatedAt       time.Time        `json:"updated_at"`
}

type GikiWalletStudentProfile struct {
	UserID        uuid.UUID   `json:"user_id"`
	RegID         string      `json:"reg_id"`
	DegreeProgram pgtype.Text `json:"degree_program"`
	BatchYear     pgtype.Int4 `json:"batch_year"`
}

type GikiWalletTransaction struct {
	ID          uuid.UUID   `json:"id"`
	Type        string      `json:"type"`
	ReferenceID string      `json:"reference_id"`
	Description pgtype.Text `json:"description"`
	CreatedAt   time.Time   `json:"created_at"`
}

type GikiWalletUser struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PhoneNumber  string      `json:"phone_number"`
	AuthProvider string      `json:"auth_provider"`
	ExternalID   pgtype.Text `json:"external_id"`
	PasswordHash string      `json:"password_hash"`
	PasswordAlgo string      `json:"password_algo"`
	IsActive     bool        `json:"is_active"`
	IsVerified   bool        `json:"is_verified"`
	UserType     string      `json:"user_type"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type GikiWalletWallet struct {
	ID        uuid.UUID   `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	Name      pgtype.Text `json:"name"`
	Type      pgtype.Text `json:"type"`
	Status    string      `json:"status"`
	Currency  string      `json:"currency"`
	CreatedAt time.Time   `json:"created_at"`
}
