import { apiClient } from '@/lib/axios';
import { User, UsersPaginationResponse } from './schema';

export const UserService = {
    listUsers: async (
        page = 1,
        pageSize = 100,
        search = '',
        userType = '',
        filterStatus = ''
    ): Promise<UsersPaginationResponse> => {
        const { data } = await apiClient.get<UsersPaginationResponse>('/admin/users', {
            params: {
                page,
                page_size: pageSize,
                search,
                user_type: userType === 'all' ? '' : userType,
                filter_status: filterStatus === 'all' ? '' : filterStatus,
            },
        });
        return data;
    },

    updateUserStatus: async (userId: string, isActive: boolean): Promise<User> => {
        const { data } = await apiClient.patch<User>(`/admin/users/${userId}/status`, {
            is_active: isActive,
        });
        return data;
    },

    approveUser: async (userId: string): Promise<User> => {
        const { data } = await apiClient.post<User>(`/admin/users/${userId}/approve`);
        return data;
    },

    rejectUser: async (userId: string): Promise<void> => {
        await apiClient.post(`/admin/users/${userId}/reject`);
    },
    createUser: async (data: Partial<User>): Promise<User> => {
        const { data: response } = await apiClient.post<User>('/admin/users', {
            ...data,
            // Password will be auto-generated by backend and emailed to user
        });
        return response;
    },

    updateUser: async (userId: string, data: Partial<User>): Promise<User> => {
        const { data: response } = await apiClient.put<User>(`/admin/users/${userId}`, data);
        return response;
    },

    deleteUser: async (userId: string): Promise<void> => {
        await apiClient.delete(`/admin/users/${userId}`);
    },
};

