// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package wallet_db

import (
	"context"

	"github.com/google/uuid"
)

const createLedgerEntry = `-- name: CreateLedgerEntry :one

INSERT INTO giki_wallet.ledger (wallet_id, amount, transaction_type, reference_id)
VALUES ($1, $2, $3, $4)
RETURNING id, wallet_id, amount, transaction_type, reference_id, description, created_at
`

type CreateLedgerEntryParams struct {
	WalletID        uuid.UUID                         `json:"wallet_id"`
	Amount          int64                             `json:"amount"`
	TransactionType GikiWalletTransactionCategoryType `json:"transaction_type"`
	ReferenceID     string                            `json:"reference_id"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (GikiWalletLedger, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry,
		arg.WalletID,
		arg.Amount,
		arg.TransactionType,
		arg.ReferenceID,
	)
	var i GikiWalletLedger
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Amount,
		&i.TransactionType,
		&i.ReferenceID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createWallet = `-- name: CreateWallet :one

INSERT INTO giki_wallet.wallets (user_id)
VALUES ($1)
RETURNING id, user_id, status, currency, created_at
`

func (q *Queries) CreateWallet(ctx context.Context, userID uuid.UUID) (GikiWalletWallet, error) {
	row := q.db.QueryRow(ctx, createWallet, userID)
	var i GikiWalletWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getLedgerEntriesByReference = `-- name: GetLedgerEntriesByReference :many

SELECT id, wallet_id, amount, transaction_type, reference_id, description, created_at FROM giki_wallet.ledger
WHERE reference_id = $1
`

func (q *Queries) GetLedgerEntriesByReference(ctx context.Context, referenceID string) ([]GikiWalletLedger, error) {
	rows, err := q.db.Query(ctx, getLedgerEntriesByReference, referenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GikiWalletLedger
	for rows.Next() {
		var i GikiWalletLedger
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Amount,
			&i.TransactionType,
			&i.ReferenceID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWallet = `-- name: GetWallet :one
SELECT id, user_id, status, currency, created_at FROM giki_wallet.wallets
WHERE user_id = $1
`

func (q *Queries) GetWallet(ctx context.Context, userID uuid.UUID) (GikiWalletWallet, error) {
	row := q.db.QueryRow(ctx, getWallet, userID)
	var i GikiWalletWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletBalance = `-- name: GetWalletBalance :one

SELECT COALESCE(SUM(amount), 0)::bigint as balance
FROM giki_wallet.ledger
WHERE wallet_id = $1
`

func (q *Queries) GetWalletBalance(ctx context.Context, walletID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getWalletBalance, walletID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}
