// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package wallet_db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (GikiWalletLedger, error)
	CreateTransactionHeader(ctx context.Context, arg CreateTransactionHeaderParams) (CreateTransactionHeaderRow, error)
	CreateWallet(ctx context.Context, arg CreateWalletParams) (GikiWalletWallet, error)
	GetLedgerEntriesByReference(ctx context.Context, referenceID string) ([]GetLedgerEntriesByReferenceRow, error)
	GetSystemWalletByName(ctx context.Context, arg GetSystemWalletByNameParams) (GikiWalletWallet, error)
	GetWallet(ctx context.Context, userID pgtype.UUID) (GikiWalletWallet, error)
	GetWalletBalanceSnapshot(ctx context.Context, walletID uuid.UUID) (int64, error)
	GetWalletForUpdate(ctx context.Context, id uuid.UUID) (GikiWalletWallet, error)
}

var _ Querier = (*Queries)(nil)
