// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package wallet_db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (GikiWalletLedger, error)
	CreateWallet(ctx context.Context, userID uuid.UUID) (GikiWalletWallet, error)
	GetLedgerEntriesByReference(ctx context.Context, referenceID string) ([]GikiWalletLedger, error)
	GetWallet(ctx context.Context, userID uuid.UUID) (GikiWalletWallet, error)
	GetWalletBalance(ctx context.Context, walletID uuid.UUID) (int64, error)
}

var _ Querier = (*Queries)(nil)
