// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package transport_db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTrip(ctx context.Context, arg CreateTripParams) (uuid.UUID, error)
	CreateTripStop(ctx context.Context, arg CreateTripStopParams) error
	GetAllRoutes(ctx context.Context) ([]GetAllRoutesRow, error)
	GetRouteStopsDetails(ctx context.Context, id uuid.UUID) ([]GetRouteStopsDetailsRow, error)
	GetRouteWeeklySchedule(ctx context.Context, routeID uuid.UUID) ([]GetRouteWeeklyScheduleRow, error)
	GetUpcomingTripsByRoute(ctx context.Context, routeID uuid.UUID) ([]GetUpcomingTripsByRouteRow, error)
}

var _ Querier = (*Queries)(nil)
